name = "anthropic-proxy"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/anthropic-proxy/./target/wasm32-unknown-unknown/release/anthropic_proxy.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/anthropic-proxy/init.json"

[[handler]]
type = "message-server"

[[handler]]
type = "runtime"

[[handler]]
type = "store"

[[handler]]
type = "http-client"

[[handler]]
type = "environment"
allowed_vars = ["ANTHROPIC_API_KEY"]
allow_list_all = false

[[handler]]
type = "timing"
max_sleep_duration = 3600000
min_sleep_duration = 1
