name = "anthropic-proxy"
component_path = "/nix/store/gf49ixka5d0dcxkyii70rjnkq56cac4d-anthropic-proxy-0.1.0/lib/anthropic-proxy.wasm"
short_description = "A proxy actor for interacting with the Anthropic API"
init_state = "/Users/colinrozzi/work/actor-registry/init.json"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]

[[handlers]]
type = "http-client"

[handlers.config]
